import { chromium } from '@playwright/test'
const nav = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const pg = await nav.newPage({ viewport: { width: 1280, height: 1000 } })
await pg.goto('http://127.0.0.1:3402/', { waitUntil: 'networkidle' })
const n = await pg.locator('details[data-ciclo]').count()
console.log('semanas visíveis para o visitante:', n)
await pg.locator('#registro').scrollIntoViewIfNeeded()
await pg.waitForTimeout(600)
await pg.screenshot({ path: '/tmp/claude-0/-home-user-projeto-6/cba11fab-dee0-58c1-b5df-bdb1b88cd196/scratchpad/vitrine.png' })
await nav.close()
